import { VideoProps } from '../types';

export const animations: VideoProps[] = [
  {
    id: '709083398',
    src: 'https://player.vimeo.com/video/709083398?h=69a1ed8380&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'Maritime',
    client: 'Vaisala',
    description:
      '観測機器メーカーVaisala（フィンランド）の海上気象観測機器に関する解説動画',
    credit1: ['Execution', 'Oskari Friman'],
    credit2: ['Production', 'Oskari Friman & Anssi Heikka'],
    thumbnailSrc: 'assets/thumbnails/vaisala.png',
  },
  {
    id: '703651979',
    src: 'https://player.vimeo.com/video/703651979?h=dd85ef1b45&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'Swaippaajat',
    client: 'Etuovi.com',
    description:
      'ソーシャルメディア、屋外広告用のアニメーションコマーシャル動画',
    credit1: ['Execution', 'Oskari Friman'],
    credit2: ['Idea', 'Oskari Friman & Ilmari Lehtonen'],
    thumbnailSrc: 'assets/thumbnails/etuovi.png',
  },
  {
    id: '703652607',
    src: 'https://player.vimeo.com/video/703652607?h=f254f8f31e&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'Yksityisleasing',
    client: 'Autotalli.com',
    description: 'カーリースに関する解説動画',
    credit1: ['Execution', 'Oskari Friman'],
    credit2: ['Idea', 'Oskari Friman & Ilmari Lehtonen'],
    thumbnailSrc: 'assets/thumbnails/autotalli.png',
  },
  {
    id: '703652805',
    src: 'https://player.vimeo.com/video/703652805?h=d1150f951a&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'RDR',
    client: 'F-secure',
    description: 'ソーシャルメディア向けアニメーションコマーシャル動画',
    credit1: ['Execution', 'Oskari Friman'],
    credit2: ['Idea and screenwriting', 'Joni Mussalo & Oskari Friman'],
    thumbnailSrc: 'assets/thumbnails/fsecure.png',
  },
  {
    id: '706890718',
    src: 'https://player.vimeo.com/video/706890718?h=47ac806344&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'Audience Engine',
    client: 'Clear Channel',
    description:
      '屋外広告会社Clearchannel向けのアニメーションと実写動画を使った解説動画',
    credit1: ['Filming and animation', 'Oskari Friman'],
    credit2: ['Script', 'Tapio Haaja & Oskari Friman'],
    credit3: ['Drone pilot', 'Miika Räty'],
    thumbnailSrc: 'assets/thumbnails/clearchannel.png',
  },
  {
    id: '703652355',
    src: 'https://player.vimeo.com/video/703652355?h=025a4e4f0a&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'Animators wanted!',
    client: 'Videolle',
    description:
      '映像制作会社Videolle（フィンランド）向けのアニメーター採用動画.目に留まり、印象に残るような動画を制作',
    credit1: ['Execution', 'Oskari Friman'],
    credit2: ['Idea', 'Oskari Friman'],
    thumbnailSrc: 'assets/thumbnails/videolle.png',
  },
];

export const videos: VideoProps[] = [
  {
    id: '702311317',
    src: 'https://player.vimeo.com/video/702311317?h=63e1d37b08&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'Industrial coatings',
    client: 'Teknos',
    description:
      '塗料・コーティング材を手掛けるTeknos（フィンランド）向けのコマーシャル動画',
    credit1: ['Filming & edit', 'Oskari Friman'],
    credit2: ['Production', 'Petri Lyytikäinen & Oskari Friman'],
    thumbnailSrc: 'assets/thumbnails/teknos.png',
  },
  {
    id: '709084419',
    src: 'https://player.vimeo.com/video/709084419?h=5bdf5ddb21&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'Pyörähuolto',
    client: 'Baiks',
    description:
      '自転車を友達のように大切に扱おうというメッセージが込められた自転車会社のコマーシャル動画.',
    credit1: ['Filming & edit', 'Oskari Friman'],
    credit2: ['Director and screenwrite', 'Henna Seppälä'],
    credit3: ['Gaffer and grip', 'Riku Niemi'],
    thumbnailSrc: 'assets/thumbnails/baiks.png',
  },
  {
    id: '709084937',
    src: 'https://player.vimeo.com/video/709084937?h=5ae1e48e24&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'Of AI',
    client: 'Elements',
    description:
      'AI(人工知能)が学べるフリーコースに関するアニメーションと実写動画を使ったコマーシャル動画',
    credit1: ['Edit & animation', 'Oskari Friman'],
    credit2: ['Filming', 'Oskari Friman & Riku Niemi'],
    credit3: ['Screenwriter', 'Joni Mussalo'],
    credit4: ['Producer', 'Tuomas Vuori'],
    thumbnailSrc: 'assets/thumbnails/elements.png',
  },
  {
    id: '13276823',
    src: 'https://player.vimeo.com/video/713276823?h=6d1e564ae7&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'Toimii!',
    client: 'Hobby hall',
    description:
      '趣味用具専門店hobby hall（フィンランド）向けのコマーシャル動画',
    credit1: ['Filming & edit', 'Oskari Friman'],
    credit2: ['Directo', 'Petri Lyytikäine'],
    credit3: ['Screenwriter', 'Joni Mussalo'],
    credit4: ['Gaffe', 'Riku Niemi'],
    credit5: ['AC', 'Anssi Tiusanen'],
    thumbnailSrc: 'assets/thumbnails/hobbyhall.png',
  },
  {
    id: '703204618',
    src: 'https://player.vimeo.com/video/703204618?h=e88625cf5b&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'Paluu tulevaisuuteen',
    client: 'Uber',
    description: 'Uber（ウーバー）向けのコマーシャル動画',
    credit1: ['Filming, editing & VFX', 'Oskari Friman'],
    credit2: ['Director', 'Petri Lyytikäinen'],
    credit3: ['Screenwriter and producer', 'Joni Mussalo'],
    credit4: ['Gaffer', 'Elias Koskinen'],
    thumbnailSrc: 'assets/thumbnails/uber.png',
  },
  {
    id: '713274842',
    src: 'https://player.vimeo.com/video/713274842?h=740b618adf&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
    title: 'Kylässä elämänturvaajalla',
    client: 'Lähitapiola',
    description:
      '保険サービスを提供する金融グループ会社Lähitapiola（フィンランド）で働く従業員のショートドキュメンタリー動画',
    credit1: ['Filming & edit', 'Oskari Friman'],
    credit2: ['Director and producer', 'Aki Kuukasjärvi'],
    thumbnailSrc: 'assets/thumbnails/lahitapiola.png',
  },
];
